name: Multiple Build
concurrency:
  group: multiple_build_${{ github.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
      - "docs/**"
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"

env:
  ANTLR_4_13: 4.13.1
  JAVET_SANITIZER_VERSION: 0.1.0

jobs:
  build_for_antlr_4_13:
    name: Build for Antlr v4.13.x
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Setup JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 8

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2

    - name: Build the Artifact
      run: |
        gradle build
        gradle javadoc

    - name: Upload the Artifact
      uses: actions/upload-artifact@v3
      with:
        name: javet-sanitizer-${{ env.JAVET_SANITIZER_VERSION }}-antlr-${{ env.ANTLR_4_13 }}
        path: build/libs/*.jar
